import of release workflow from provider scafolding
oVirt/terraform-provider-ovirt pull request #231
Opened 2020-10-05 12:11 UTC by attachmentgenie

As taken from terraform-provider-scaffolding

This workflow creates a draft release with all the required binary artifacts that the hashicorp registry requires. It requires an admin to set a github secret called GPG_FINGERPRINT which is the gpg key with which the binaries will be signed

This workflow is a required step for achieving #230

2020-11-24 10:25 UTC, dvzrv commented
Is there someone that can merge this pull request? :)

2021-01-05 10:10 UTC, emesika commented
Please rebase your patch on latest master

2021-01-05 12:12 UTC, attachmentgenie commented
> rebase is failing on "trailing whitespaces", please remove them

@emesika i have now rebased, but i am not entirely sure what you mean with failing on trailing white space. the rebase went ok, is there any check i can do to verify/validate/reproduce?

2021-01-05 23:37 UTC, emesika requested changes

2021-01-05 23:37 UTC, emesika commented on .github/workflows/release.yml
> +# This uses an action (paultyng/ghaction-import-gpg) that assumes you set your
Please remove trailing white space from end

2021-01-05 23:37 UTC, emesika commented on .github/workflows/release.yml
> +# You will need to pass the `--batch` flag to `gpg` in your signing step
Please remove trailing white space from end

2021-01-05 23:39 UTC, emesika commented
> > rebase is failing on "trailing whitespaces", please remove them
> 
> @emesika i have now rebased, but i am not entirely sure what you mean with failing on trailing white space. the rebase went ok, is there any check i can do to verify/validate/reproduce?

patch is tested by running 'git apply' on your patch above master , 'git apply' fails on trailing white-spaces

2021-01-06 09:36 UTC, attachmentgenie commented on .github/workflows/release.yml
> +# This uses an action (paultyng/ghaction-import-gpg) that assumes you set your
done

2021-01-06 09:36 UTC, attachmentgenie commented on .github/workflows/release.yml
> +# You will need to pass the `--batch` flag to `gpg` in your signing step
done

2021-01-06 14:02 UTC, merged